"""empty message

Revision ID: a7f909bd1953
Revises: 0d3344899a3b
Create Date: 2024-04-26 16:07:12.935089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f909bd1953'
down_revision = '0d3344899a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_platform_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_post_platform', 'platform', ['post_platform_id'], ['platform_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_platform', type_='foreignkey')
        batch_op.drop_column('post_platform_id')

    # ### end Alembic commands ###
